name: Build APK

on:
  push:
    branches:
      - master  # تغيير "main" إلى "master"
  pull_request:
    branches:
      - master  # تغيير "main" إلى "master"

jobs:
  build:
    runs-on: ubuntu-latest  # سيعمل على بيئة Ubuntu في GitHub
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Set up Android SDK
        run: |
          sudo apt-get install -y wget
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_ENV
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-30" "build-tools;30.0.3"

      - name: Build APK
        run: |
          cd path/to/your/project
          ./gradlew assembleRelease  # أو حسب تهيئة Gradle الخاصة بمشروعك

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-app-apk
          path: path/to/your/project/app/build/outputs/apk/release/app-release.apk
