name: Build APK

on:
  push:
    branches:
      - master  # تأكد من أن الفرع هو "master"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # بيئة البناء على Ubuntu
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'  # استخدام Zulu OpenJDK بدلاً من AdoptOpenJDK

      - name: Set up Android SDK
        run: |
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk/cmdline-tools
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin" >> $GITHUB_ENV
          # تحديث المسار بعد فك الضغط
          echo "export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin" >> $GITHUB_ENV
          # قبول الترخيص
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-30" "build-tools;30.0.3"

      - name: Build APK
        run: |
          cd path/to/your/project
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my-app-apk
          path: path/to/your/project/app/build/outputs/apk/release/app-release.apk
